sudo: false
language: cpp
compiler:
  - gcc
env:
  matrix:
    - FUZZ=1
    - CORBAEMICRO=1 ACEFORTAO=0
    - CORBAECOMPACT=1 ACEFORTAO=0
    - ACEFORTAO=1
    - CCMLW=0 ACEFORTAO=0
    - CCMLW=1 ACEFORTAO=0
    - CCMNOEVENT=1 ACEFORTAO=0
    - ACETESTS=1 ACEFORTAO=0
    - USES_WCHAR=1
  global:
    - ACE_ROOT=$TRAVIS_BUILD_DIR/ACE
    - TAO_ROOT=$TRAVIS_BUILD_DIR/TAO
    - CIAO_ROOT=$TRAVIS_BUILD_DIR/CIAO
    - DANCE_ROOT=$TRAVIS_BUILD_DIR/DAnCE
    - MPC_ROOT=$TRAVIS_BUILD_DIR/MPC
    - LD_LIBRARY_PATH=$ACE_ROOT/lib:$LD_LIBRARY_PATH
addons:
  apt:
    packages:
    - libssl-dev
    - libxerces-c-dev
before_install:
  - git clone git://github.com/DOCGroup/MPC.git
branches:
  only:
    - master
before_script:
  - export
  - echo -e "#include \"ace/config-linux.h\"" >> $ACE_ROOT/ace/config.h
  - echo -e "workspace {\n\$(TAO_ROOT)/TAO_ACE.mwc\n\$(TAO_ROOT)/tests/Hello\n" >> $TRAVIS_BUILD_DIR/travis.mwc
  - if [ "$ACEFORTAO" == "0" ]; then echo -e "\$(CIAO_ROOT)/CIAO_TAO_DAnCE.mwc\n" >> $TRAVIS_BUILD_DIR/travis.mwc; fi
  - if [ "$ACETESTS" == "1" ]; then echo -e "\$(ACE_ROOT)/tests\n" >> $TRAVIS_BUILD_DIR/travis.mwc; fi
  - echo -e "}\n" >> $TRAVIS_BUILD_DIR/travis.mwc
  - if [ "$CORBAEMICRO" == "1" ]; then echo -e "corba_e_micro=1" >> $ACE_ROOT/include/makeinclude/platform_macros.GNU; fi
  - if [ "$CORBAEMICRO" == "1" ]; then echo -e "corba_e_micro=1" >> $ACE_ROOT/bin/MakeProjectCreator/config/default.features; fi
  - if [ "$CORBAECOMPACT" == "1" ]; then echo -e "corba_e_compact=1" >> $ACE_ROOT/include/makeinclude/platform_macros.GNU; fi
  - if [ "$CORBAECOMPACT" == "1" ]; then echo -e "corba_e_compact=1" >> $ACE_ROOT/bin/MakeProjectCreator/config/default.features; fi
  - if [ "$ACEFORTAO" == "1" ]; then echo -e "ace_for_tao=1" >> $ACE_ROOT/include/makeinclude/platform_macros.GNU; fi
  - if [ "$ACEFORTAO" == "1" ]; then echo -e "ace_for_tao=1" >> $ACE_ROOT/bin/MakeProjectCreator/config/default.features; fi
  - if [ "$CCMLW" == "1" ]; then echo -e "ccm_lw=1" >> $ACE_ROOT/bin/MakeProjectCreator/config/default.features; fi
  - if [ "$CCMNOEVENT" == "1" ]; then echo -e "ccm_noevent=1" >> $ACE_ROOT/bin/MakeProjectCreator/config/default.features; fi
  - if [ "$USES_WCHAR" == "1" ]; then echo -e "uses_wchar=1" >> $ACE_ROOT/bin/MakeProjectCreator/config/default.features; fi
  - echo -e "xerces3=1\nssl=1\nipv6=1\n" >> $ACE_ROOT/include/makeinclude/platform_macros.GNU
  - echo -e "xerces3=1\nssl=1\n" >> $ACE_ROOT/bin/MakeProjectCreator/config/default.features
  - echo -e "TAO/tests/Hello/run_test.pl" >> $TAO_ROOT/bin/travis-ci.lst
  - if [ "$CXX" == "g++" ]; then echo -e "include \$(ACE_ROOT)/include/makeinclude/platform_linux.GNU" >> $ACE_ROOT/include/makeinclude/platform_macros.GNU; fi
  - if [ "$CXX" == "clang++" ]; then echo -e "include \$(ACE_ROOT)/include/makeinclude/platform_linux_clang.GNU" >> $ACE_ROOT/include/makeinclude/platform_macros.GNU; fi
  - cat $TRAVIS_BUILD_DIR/travis.mwc
  - cat $ACE_ROOT/bin/MakeProjectCreator/config/default.features
  - cat $ACE_ROOT/ace/config.h
  - cat $ACE_ROOT/include/makeinclude/platform_macros.GNU

script:
  - if [ "$FUZZ" == "1" ]; then exec perl $ACE_ROOT/bin/fuzz.pl; fi
  - perl $ACE_ROOT/bin/mwc.pl -type gnuace -workers 2 travis.mwc
  - make -j 2
  - perl $ACE_ROOT/bin/auto_run_tests.pl -l $TAO_ROOT/bin/travis-ci.lst

